### ISSUE TITLE
MacVim fails to built on OS X with non Framework Python

### ISSUE THREAD

**Issue by al3xandru** [macvim-dev/macvim#386]
MacVim seems to require the Framework Python for installing on OS X (macOS Siera 10.12).

I tried installing MacVim snapshot 111 through homebrew against a newer Python version (2.7.12) and it fails:

```
brew upgrade --build-from-source --with-custom-python --with-lua --with-cscope macvim
...
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enab
==> make
Last 15 lines from /Users/apopescu/Library/Logs/Homebrew/macvim/02.make:
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/json.o json.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/main.o main.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/memfile.o memfile.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/message.o message.c
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -I/Users/apopescu/.pyenv/versions/2.7.12/include/python2.7 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       version.c -o objects/version.o
 env LD_RUN_PATH=/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error -L/usr/local/lib 	-o Vim objects/arabic.o objects/buffer.o objects/blowfish.o objects/charset.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_beval.o objects/pty.o objects/gui_macvim.o objects/MMBackend.o objects/MacVim.o objects/if_lua.o  objects/if_perl.o objects/if_perlsfio.o objects/if_python.o   objects/if_ruby.o objects/os_macosx.o objects/os_mac_conv.o  objects/netbeans.o objects/channel.o  objects/json.o objects/main.o objects/memfile.o objects/message.o -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/opt/lua/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -L/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error   -framework Ruby
Undefined symbols for architecture x86_64:
  "_PyUnicodeUCS2_AsEncodedString", referenced from:
      _StringToLine in if_python.o
      _StringToChars in if_python.o
      __ConvertFromPyObject in if_python.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've seen this problem in the past with `vim` itself but it seems like it was addressed in https://github.com/vim/vim/pull/980. I did install vim using the same command as above and it worked.

**Comment by splhack** [comment]
You don't need to build MacVim by yourself in order to use pyenv Python 2.7.12 for if_python. Just use binary release https://github.com/macvim-dev/macvim/releases/latest with the settings.

    let $PYTHONHOME=$HOME."/.pyenv/versions/2.7.12"
    set pythondll=$HOME/.pyenv/versions/2.7.12/lib/libpython2.7.dylib

And MacVim build is just fine with pyenv 2.7.12.

    $ env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.12
    $ pyenv versions
    * system (set by /Users/foo/.pyenv/version)
      2.7.12

    $ vi_cv_path_python=$HOME/.pyenv/versions/2.7.12/bin/python ./configure --with-features=huge --enable-multibyte --enable-pythoninterp=yes --with-python-config-dir=$HOME/.pyenv/versions/2.7.12

    $ cat src/auto/config.mk

    PYTHON_SRC	= if_python.c
    PYTHON_OBJ	= objects/if_python.o
    PYTHON_CFLAGS	= -I/Users/foo/.pyenv/versions/2.7.12/include/python2.7 -DPYTHON_HOME='"/Users/foo/.pyenv/versions/2.7.12"' -fPIE
    PYTHON_LIBS	= -L/Users/foo/.pyenv/versions/2.7.12 -lpython2.7
    PYTHON_CONFDIR	= /Users/foo/.pyenv/versions/2.7.12
    PYTHON_GETPATH_CFLAGS = -DPYTHONPATH='":/Users/foo/.pyenv/versions/2.7.12/lib/python27.zip:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/plat-darwin:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/plat-mac:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/plat-mac/lib-scriptpackages:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/lib-tk:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/lib-old:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload:/Users/foo/.pyenv/versions/2.7.12/lib/python2.7/site-packages"' -DPREFIX='"/Users/foo/.pyenv/versions/2.7.12"' -DEXEC_PREFIX='"/Users/foo/.pyenv/versions/2.7.12"'
    
    $ make

    ** BUILD SUCCEEDED **

**Comment by al3xandru** [comment]
Where are these settings going?

```
let $PYTHONHOME=$HOME."/.pyenv/versions/2.7.12"
set pythondll=$HOME/.pyenv/versions/2.7.12/lib/libpython2.7.dylib
```

If set in `.vimrc`, MacVim complains that `pythondll` is an unknown option.

**Comment by al3xandru** [comment]
I downloaded the latest snapshot, set those values in `.vimrc`, but I see a long list of errors in Messages:

```
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
Traceback (most recent call last):
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "<string>", line 1, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "/Users/apopescu/.vim/bundle/vim-pyenv/initialize.py", line 12, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
    import pyenv_vim
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "/Users/apopescu/.vim/bundle/vim-pyenv/pyenv_vim.py", line 4, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
    import subprocess
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/subprocess.py", line 430, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
    import pickle
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/pickle.py", line 34, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
    import struct
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/struct.py", line 1, in <module>
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
    from _struct import *
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
ImportError: dlopen(/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so, 2): Symbol not found: _PyUnicodeUCS4_AsEncodedString
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  Referenced from: /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
  Expected in: flat namespace
Error detected while processing function <SNR>156_init[14]..<SNR>156_exec_file:
line    3:
 in /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so
Error detected while processing function pyenv#activate[2]..<SNR>149_activate[15]..pyenv#python#exec_code[1]..<SNR>156_exec_code:
line    4:
Traceback (most recent call last):
Error detected while processing function pyenv#activate[2]..<SNR>149_activate[15]..pyenv#python#exec_code[1]..<SNR>156_exec_code:
line    4:
  File "<string>", line 1, in <module>
Error detected while processing function pyenv#activate[2]..<SNR>149_activate[15]..pyenv#python#exec_code[1]..<SNR>156_exec_code:
line    4:
NameError: name 'pyenv_vim' is not defined
```

**Comment by al3xandru** [comment]
_Update_: I did follow the instruction for building it locally and while the compilation works, when opening python files I still get errors: 

```
E518: Unknown option: pythondll=$HOME/.pyenv/versions/2.7.12/lib/libpython2.7.dylib
"~/Dropbox/workspace/miscellaneous/dotfiles/bin/imdb.py" 491L, 17802C
Error detected while processing /Users/apopescu/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/apopescu/.vim/bundle/python-mode/pymode/virtualenv.py", line 5, in <module>
    from .environment import env
  File "/Users/apopescu/.vim/bundle/python-mode/pymode/environment.py", line 6, in <module>
    import json
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: dlopen(/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so, 2): Symbol not found: _PyUnicodeUCS4_AsEncodedString
  Referenced from: /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so
  Expected in: flat namespace
 in /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/_struct.so
Error detected while processing /Users/apopescu/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   10:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/apopescu/.vim/bundle/python-mode/pymode/utils.py", line 4, in <module>
    import threading
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/threading.py", line 13, in <module>
    from collections import deque as _deque
  File "/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/collections.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: dlopen(/Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/operator.so, 2): Symbol not found: __PyUnicodeUCS4_AsDefaultEncodedString
  Referenced from: /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/operator.so
  Expected in: flat namespace
 in /Users/apopescu/.pyenv/versions/2.7.12/lib/python2.7/lib-dynload/operator.so
Error detected while processing function jedi#init_python:
line    7:
Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(pyfile):Traceback (most recent call last): (in function jedi#init_python[3]..<SNR>158_init_py
thon[48]..jedi#setup_py_version, line 16) 
```

**Comment by splhack** [comment]
I can't repro any of those.

.vimrc

    let $PYTHONHOME=$HOME."/.pyenv/versions/2.7.12"
    set pythondll=$HOME/.pyenv/versions/2.7.12/lib/libpython2.7.dylib
    execute pathogen#infect()

plugins

    .vim/autoload/pathogen.vim
    .vim/bundle/jedi-vim/
    .vim/bundle/vim-pyenv/

**Comment by al3xandru** [comment]
I came to update my previous comments as after looking a bit more into the errors I realized that the placement of those 2 conf options is important.  _Thanks for following up on this._

Now, setting `$PYTHONHOME` seems to impact the behavior of `vim-pyenv` which no longer is able to determine the actual pyenv version and set things correctly. I'm wondering if once again experimenting with the order will lead to better results.

**Comment by al3xandru** [comment]
I cannot tell if this is a good solution, but I ended up having the following:

```vim
if has('gui') && has('mac')
    if executable("pyenv")
        let cmd = 'pyenv version-name'
        let pyenv=substitute(system(cmd), '[\]\|[[:cntrl:]]', '', 'g')
        let cmd = 'python -c "import sys;vt=sys.version_info;print \"%s.%s.%s\" % (vt[0], vt[1], vt[2])"'
        let pyver=substitute(system(cmd), '[\]\|[[:cntrl:]]', '', 'g')
        let $PYTHONHOME=$HOME . "/.pyenv/versions/" . pyver
        let $PYTHONPATH=$HOME . "/.pyenv/versions/" . pyenv . "/lib/python2.7/site-packages/"
        set pythondll=$PYTHONHOME/lib/libpython2.7.dylib
    endif
endif
```

_Note that it won't work with Python 3.x as the `pythondll` doesn't account for the python version yet, but that shouldn't be hard to change._
